### ISSUE TITLE
Error while training on homemade dataset

### ISSUE THREAD

**Issue by hadware** [felixkreuk/UnsupSeg#2] opened 2021-01-15 00:14 UTC
Hey @felixkreuk,

Thanks a lot for publishing your code. I'm willing to use it on my own data (and i've been sucessfully been making inferences). I also wanted to compare this model's inference results when it's being retrained on my own data. I thus converted my data to the TIMIT format that you're detailing in the README. I've also segmented my audio files (that are quite long compared to the TIMIT database's files) into 5-seconds segments. **To be able to run the training phase on my own data, i've configured the `timit_path` in the `conf/config.yaml` file to point to my dataset**. I'm thus training the model using the following command:

```python
python train.py data=timit
```

The training "mostly" works, until it fails during the 1st epoch, displaying the following error:
```python
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    main()
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/hydra/main.py", line 20, in decorated_main
    run_hydra(
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/hydra/_internal/utils.py", line 171, in run_hydra
    hydra.run(
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 82, in run
    return run_job(
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "main.py", line 62, in main
    trainer.fit(solver)
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 887, in fit
    self.run_pretrain_routine(model)
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1015, in run_pretrain_routine
    self.train()
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 347, in train
    self.run_training_epoch()
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 451, in run_training_epoch
    self.run_evaluation(test_mode=self.testing)
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 377, in run_evaluation
    eval_results = self._evaluate(self.model, dataloaders, max_batches, test_mode)
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 321, in _evaluate   
    eval_results = model.validation_end(outputs)
  File "/home/htiteux/Code/UnsupSeg/solver.py", line 208, in validation_end
    return self.generic_eval_end(outputs, 'val')
  File "/home/htiteux/Code/UnsupSeg/solver.py", line 155, in generic_eval_end
    (precision, recall, f1, rval), (width, prominence, distance) = self.pr[pred_type][mode].get_stats()
  File "/home/htiteux/Code/UnsupSeg/utils.py", line 136, in get_stats
    min_dist = np.abs(y - yhat_i).min()
  File "/home/htiteux/.conda/envs/unsup_seg/lib/python3.8/site-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
Epoch 1:  20%|█▉        | 158/791 [26:46<1:47:17, 10.17s/it, loss=0.212, v_num=144405]
```

I tried using PDB to investigate what might be wrong (say, for instance, a faulty batch sample) but my knowledge of `pytorch-lightning` was too sparse to lead me to anything helpful. Since it's your code, do you have any idea what might be causing this, and how to correct it?

NOTE: trying to train the model on the TIMIT dataset works on my setup. Thus, my guess is that it has something to do with my data.

**Comment by felixkreuk** [comment] 2021-01-17 13:09
Hi @hadware , nice to know you're finding our code useful :)

Regarding your issue, it does not seem to be related to pytorch-lightning. 
Seems that the issue is located here:
```
  File "/home/htiteux/Code/UnsupSeg/utils.py", line 136, in get_stats
    min_dist = np.abs(y - yhat_i).min()
```
Numpy is saying that we are taking the min element of a zero-sized array. Could it be that you segmented your original audio in such a way to some segments contain no phoneme boundaries? For example, segments that contain only silence.

**Comment by hadware** [comment] 2021-01-17 18:00
> Could it be that you segmented your original audio in such a way to some segments contain no phoneme boundaries? 

That is totally possible! i thought that these "negative" examples could help the model in any case, but I'll remove them for now.

**Comment by felixkreuk** [comment] 2021-01-17 18:24
That's interesting. 
Though I'm not sure what will be the effect of the negative samples (Eq. 1) when the entire segment has the same phonetical content (silence). You see, when we sample for a random frame from the same audio segment, our assumption is that it comes from a different phoneme, hence we label it as a "negative sample". Nevertheless, you can definitely try that, you'll just need to adjust the piece of code that calculates the metrics (`get_stats` function). Specifically, allow for zero length labels (no phoneme boundaries).

**Comment by felixkreuk** [comment] 2021-01-18 10:03
I'm closing this issue for now. Let me know if you need further assistance.

**Closed as completed by felixkreuk** 2021-01-18 10:03 UTC

**Comment by hadware** [comment] 2021-01-18 11:24
This raises a couple of questions regarding my dataset:

1. Do I need to indicate all "silences" (gaps between speech stretches) with a special silence phoneme?
2. Is there a special, dedicated value for that phoneme?
3. My dataset is phonemized using SAMPA.  My guess was that this didn't matter much, but i'd just like ot be sure.

**Comment by felixkreuk** [comment] 2021-01-18 11:29
1. Usually (at least for TIMIT) silences are annotated with a silence phoneme. In our case, we are only interested in the phoneme boundaries, the phoneme identities don't matter much.
2. For TIMIT silences are annotated using "sil" IIRC.
3. I'm not familiar with this annotation scheme. But yes, I don't see why it should matter, we only care for the boundaries really. So as long as all the boundaries are annotated that should be fine.

**Comment by hadware** [comment] 2021-01-18 12:11
Ok, thanks for your answers, i'll see if tweaking my dataset considering your input makes it work.
